#!/bin/bash
qsub -vBATCHSIZE=1,BATCHNUM=0 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=1 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=2 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=3 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=4 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=5 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=6 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=7 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=8 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=9 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=10 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=11 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=12 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=13 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=14 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=15 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=16 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=17 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=18 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=19 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=20 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=21 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=22 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=23 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=24 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=25 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=26 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=27 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=28 paralleljob_OM_alltoone_1_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=29 paralleljob_OM_alltoone_1_0.9.pbs
