#!/bin/bash
qsub -vBATCHSIZE=1,BATCHNUM=0 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=1 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=2 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=3 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=4 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=5 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=6 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=7 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=8 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=9 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=10 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=11 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=12 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=13 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=14 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=15 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=16 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=17 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=18 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=19 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=20 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=21 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=22 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=23 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=24 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=25 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=26 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=27 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=28 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
qsub -vBATCHSIZE=1,BATCHNUM=29 paralleljob_reg_OM_alltorand_0.8_0.8.pbs
