#!/bin/bash
qsub -vBATCHSIZE=1,BATCHNUM=0 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=1 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=2 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=3 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=4 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=5 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=6 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=7 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=8 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=9 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=10 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=11 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=12 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=13 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=14 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=15 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=16 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=17 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=18 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=19 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=20 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=21 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=22 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=23 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=24 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=25 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=26 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=27 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=28 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=29 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=30 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=31 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=32 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=33 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=34 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=35 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=36 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=37 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=38 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=39 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=40 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=41 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=42 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=43 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=44 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=45 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=46 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=47 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=48 paralleljob_gweot_alltorand_0.9_0.9.pbs
qsub -vBATCHSIZE=1,BATCHNUM=49 paralleljob_gweot_alltorand_0.9_0.9.pbs
